default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL'] || Rails.application.credentials.dig(Rails.env.to_sym, :database_pool) %>
  host: <%= ENV['DATABASE_HOST'] || Rails.application.credentials.dig(Rails.env.to_sym, :database_host) %>
  port: <%= ENV['DATABASE_PORT'] || Rails.application.credentials.dig(Rails.env.to_sym, :database_port) %>
  username: <%= ENV['DATABASE_USERNAME'] || Rails.application.credentials.dig(Rails.env.to_sym, :database_username) %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.dig(Rails.env.to_sym, :database_password) %>

development:
  <<: *default
  database: concurrency_theater_development

test:
  <<: *default
  database: concurrency_theater_test

production:
  <<: *default
