default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_pool) %>
  host: localhost
  port: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_port) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_password) %>

development:
  <<: *default
  database: concurrency_theater_development

test:
  <<: *default
  database: concurrency_theater_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production, :database_name) %>
